import { Cairo } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { CartAnimationProvider } from "@/contexts/CartAnimationContext";

// خط Cairo فقط
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic", "latin"],
  weight: ["400", "700"], // أو أي أوزان تحتاجها
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${cairo.variable} antialiased`}>
        <CartAnimationProvider>
        {children}

        </CartAnimationProvider>
        <Toaster richColors position="top-center" />
      </body>
    </html>
  );
}
